name: "Python Code Checker"
description: "Run tox across matrix Python versions with optional requirements files."
author: "GitCodeCheckers"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  python-version:
    description: "Python version to use."
    required: true

  file:
    description: "Optional file or directory passed to tox (if your tox.ini uses it)."
    required: false
    default: ""

  requirements:
    description: "Optional requirements file to install from (overrides requirements.txt)."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        allow-prereleases: true

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Install tox + tox-gh-actions
      shell: bash
      run: pip install tox tox-gh-actions

    - name: Install project dependencies
      shell: bash
      run: |
        # Priority 1: matrix-provided requirements file
        if [ -n "${{ inputs.requirements }}" ] && [ -f "${{ inputs.requirements }}" ]; then
          echo "Installing from matrix requirements file: ${{ inputs.requirements }}"
          pip install -r "${{ inputs.requirements }}"

        # Priority 2: fallback to requirements.txt
        elif [ -f requirements.txt ]; then
          echo "Installing from default requirements.txt"
          pip install -r requirements.txt

        # Priority 3: no requirements found
        else
          echo "No requirements file provided or found."
        fi

    - name: Run tox
      shell: bash
      run: |
        echo "Running tox."
        tox || code=$?

        # Exit code 5 = no tests collected → treat as success
        if [ "${code:-0}" = "5" ]; then
          echo "No tests collected — treating as success."
          exit 0
        fi

        # Any other non-zero exit code = real failure
        if [ -n "${code:-}" ] && [ "$code" != "0" ]; then
          echo "Tox failed with exit code $code"
          exit "$code"
        fi
